server:
  port: 80
spring:
  cloud:
    gateway:
      globalcors:
        cors-configurations:
          '[/**]':
            allowedOrigins: "*"
            allowedMethods: "*"
            # 简单跨域

            # 复杂跨域
            allowedHeaders: "*"
            allowCredentials: true

      routes:
        # /api/product/** 转给服务service-product
        - id: service-product-route
          uri: lb://service-product
          predicates:
            - Path=/admin/product/**, /search/test/**

        # /api/user/** 转给服务service-user
        - id: service-user-route
          uri: lb://service-user
          predicates:
            - Path=/api/user/**

        # /api/cart/** 转给服务service-cart
        - id: service-cart-route
          uri: lb://service-cart
          predicates:
            - Path=/api/cart/**

        # /api/order/** 转给服务service-order
        - id: service-order-route
          uri: lb://service-order
          predicates:
            - Path=/api/order/**

        - id: web-all-route
          uri: lb://web-all
          predicates:
            - Host=**.gmall.com,gmall.com

        # 分布式锁测试
        - id: test-route
          uri: lb://service-item
          predicates:
            - Path=/test1

app:
  auth:
    noAuthUrl: # 直接放行的资源
      - /js/**
      - /css/**
      - /img/**
    denyUrl: # 不可访问资源
      - /api/inner/**
    loginAuthUrl: # 需要登录才能访问的资源
      - /trade.html
      - /**/auth/**
    loginPage: http://passport.gmall.com/login.html # 登录异常,需要返回到登录页