server:
  port: 80
spring:
  cloud:
    gateway:
      globalcors:
        cors-configurations:
          '[/**]':
            allowedOrigins: "*"
            allowedMethods: "*"


      routes:
        - id: service-product-route
          uri: lb://service-product
          predicates:
            - Path=/admin/product/**
  zipkin:
    base-url: http://192.168.179.180:9411
    sender:
      type: web