server:
  port: 8000

  # 配置数据源
spring:
  datasource:
    url: jdbc:mysql://192.168.179.180:3306/gmall_product?useSSL=false
    username: root
    password: 123456
    driver-class-name: com.mysql.jdbc.Driver
    type: com.zaxxer.hikari.HikariDataSource
  servlet:
    multipart:
      max-file-size: 20MB
      max-request-size: 20MB
  profiles:
    include: sharding
#  redis:
#    host: 192.168.179.180
#    password: 123456
#    port: 6379

app:
  minio:
    endpoint: http://192.168.179.180:9000
    access-key: admin
    secret-key: admin123456
    bucket-name: mall